import Head from "next/head";
import Card from "../components/Card";
import Nav from "../components/Nav";
import useGetUser from "../hooks/useGetUser";

export default function Home() {
  const [user, isLoading, error] = useGetUser();
  if (isLoading) {
    return <div>Loading...</div>;
  }
  if (error && error.message === "No data" && !user) {
    return <div>{error.message}</div>;
  }
  return (
    <>
      <Head>
        <title>Code challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-3">
        <Nav />
        <div className="mt-3">
          <Card {...user} />
        </div>
      </main>
    </>
  );
}
