import Head from "next/head";
import Nav from "../components/Nav";
import User from "../components/User";
import useGetUsers from "../hooks/useGetUsers";

export default function Users() {
  const [users, isLoading, error] = useGetUsers();
  if (isLoading) {
    return <div>Loading...</div>;
  }
  if (error) {
    return <div>{error.message}</div>;
  }
  return (
    <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-3">
        <Nav />
        <div className="mt-3 flex flex-col items-center">
          {users.map((user) => (
            <div key={user.email}>
              <User {...user} />
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
